# Generated by Django 3.1.5 on 2021-01-15 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100, verbose_name='name')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100, verbose_name='name')),
                ('image_description', models.CharField(max_length=400, verbose_name='description')),
                ('image', models.ImageField(upload_to='images/', verbose_name='image')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='galleries.album')),
            ],
        ),
    ]
